Made a blog for solution to question of Day 1
gostudent/Letsgo pull request #15
Opened 2018-01-12 23:03 UTC by marshallKR7

2018-01-12 23:13 UTC, marshallKR7 commented
@gauthamzz there is 50 points for making blog,isn't it?
Can you clarify me please though you have stated it before.

2018-01-12 23:42 UTC, gauthamzz requested changes
That’s not how you highlight code in markdown , google and correct it

2018-01-13 00:09 UTC, marshallKR7 commented
Okk sir,doing it.

2018-01-13 03:04 UTC, mubaris requested changes

2018-01-13 03:04 UTC, mubaris commented on _posts/2018-01-13-Day-1-Question-and-Solution.md
> +### package main
`###` is for Heading as well any number of hashed from 1 to 6.

For code highlighting you have to use tilda charcter `

Read More about markdown from here - [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

2018-01-13 03:04 UTC, mubaris commented on _posts/2018-01-13-Day-1-Question-and-Solution.md
> +### package main
Highlight code properly and Change `##` proper paragraphs

2018-01-13 08:16 UTC, marshallKR7 commented
I have made the changes.Please see it.

2018-01-13 09:43 UTC, mubaris requested changes

2018-01-13 09:43 UTC, mubaris commented on _posts/2018-01-13-Day-1-Question-and-Solution.md
> +published: true
```
---
published: true
author: <username>
layout: post
title: Even-Odd turn game Solution in Go
---
```
You need to add these many info

2018-01-13 11:59 UTC, marshallKR7 commented
@mubaris updated it. :D

2018-01-13 12:33 UTC, gauthamzz commented
well anyway one post is merged. This wont be merged. But you will get points.

2018-01-13 12:33 UTC, closed without merging

2018-01-13 13:07 UTC, marshallKR7 commented
Yup its ok but i think there was some confusion as you requested me the changes in blog and after 2 hours other contestant's PR on the same issue was merged.